SELECT  INITCAP('init the cap or else') FROM DUAL;

SELECT INITCAP(21/7) FROM DUAL;

SELECT initcap(SYSDATE)  FROM DUAL;

SELECT LENGTH(1+2.14) FROM DUAL;

SELECT  LENGTH(SYSDATE) FROM DUAL;

SELECT  LPAD(1000+200.55, 14, '*') FROM DUAL;

SELECT  RPAD(1000+200.55, 14, '@') FROM DUAL;

SELECT  LPAD(SYSDATE, 20, '$#') FROM DUAL;

SELECT INSTR(3.14, '4') FROM dual;

SELECT INSTR('1#3#5#7#9#', '#')  FROM DUAL;

SELECT  INSTR('1#3#5#7#9#', '#', 5) FROM DUAL;

SELECT  INSTR('1#3#5#7#9#', '#',3, 4) FROM DUAL;

SELECT  REPLACE('1#3#5#7#9#','#', '>') FROM DUAL;

SELECT  REPLACE('1#3#5#7#9#','#') FROM DUAL;

SELECT  SUBSTR('1#3#5#7#9#', 3, 4) FROM DUAL;

SELECT  SUBSTR(SYSDATE, 4) FROM DUAL;

SELECT  SUBSTR(SYSDATE, 4, 3) FROM DUAL;

SELECT  SUBSTR(SYSDATE, -2) FROM DUAL;

SELECT  SUBSTR(SYSDATE, -6,3) FROM DUAL;

SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, hire_date)/12) 
FROM employees;

SELECT hire_date, ADD_MONTHS(hire_date, 6) AS "Review Date"
FROM employees;

SELECT LAST_DAY('01-FEB-2016')
FROM DUAL;

SELECT NEXT_DAY('12-OCT-18', 'SATURDAY') FROM DUAL;


